spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/ldt_auth
    username: role
  flyway:
    baseline-on-migrate: true
    url: jdbc:postgresql://localhost:5432/ldt_auth
    user: role
server:
  port: 8091
